import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import Ionicons from "@expo/vector-icons/Ionicons";
import { getDatabase, ref, onValue } from "firebase/database";

export default function HospitalInsights({ hospitalId = "UH-HOS-00000" }) {
  const [insight, setInsight] = useState({
    peakTime: "12 PM",
    suggestion: "Loading live hospital insights...",
    isBusy: false,
  });

  useEffect(() => {
    const db = getDatabase();

    const insightRef = ref(db, `Hospitals/${hospitalId}/insights`);
    const weeklyRef = ref(db, `Hospitals/${hospitalId}/analytics/bedUtilizationWeekly`);
    const statusRef = ref(db, `Hospitals/${hospitalId}/emergencyStatusDistribution`);

    // 1) Try direct insights node (preferred)
    const unsubInsight = onValue(insightRef, (snapshot) => {
      if (snapshot.exists()) {
        const data = snapshot.val();
        setInsight({
          peakTime: data.peakTime || "12 PM",
          suggestion:
            data.suggestion ||
            "Live analytics unavailable. Consider visiting outside typical rush hours.",
          isBusy: !!data.isBusy,
        });
      }
    });

    // 2) Fallback: derive from analytics if /insights is missing or incomplete
    const unsubWeekly = onValue(weeklyRef, (snapshot) => {
      const weekly = snapshot.exists() ? snapshot.val() : null;

      // emergencyStatusDistribution decides busy vs normal
      onValue(statusRef, (statusSnap) => {
        const statusDist = statusSnap.exists() ? statusSnap.val() : null;

        // Only apply fallback if direct insights has not provided a custom suggestion
        setInsight((prev) => {
          const base = { ...prev };

          // Derive peakTime from highest utilization day if possible
          if (weekly) {
            const dayKeys = Object.keys(weekly);
            let maxDay = null;
            let maxVal = -1;
            dayKeys.forEach((day) => {
              const val = Number(weekly[day]) || 0;
              if (val > maxVal) {
                maxVal = val;
                maxDay = day;
              }
            });

            if (maxDay) {
              // Simple mapping to a human-readable time window
              const dayLabel = maxDay.toUpperCase();
              base.peakTime = `${dayLabel} • 12–2 PM`;
            }
          }

          // Determine busy flag from emergencyStatusDistribution
          if (statusDist) {
            const busyCount = Number(statusDist.busy || 0);
            const overloadedCount = Number(statusDist.overloaded || 0);
            const normalCount = Number(statusDist.normal || 0);
            const total = busyCount + overloadedCount + normalCount;

            const busyRatio =
              total > 0 ? (busyCount + overloadedCount) / total : 0;

            base.isBusy = busyRatio >= 0.4; // heuristic
            base.suggestion =
              busyRatio >= 0.4
                ? "Recent patterns show frequent rush hours. Try booking early or avoid peak afternoons."
                : "Load is usually moderate. Walk‑in visits are likely to be smoother.";
          }

          return base;
        });
      });
    });

    return () => {
      unsubInsight();
      unsubWeekly();
    };
  }, [hospitalId]);

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Ionicons name="bulb" size={18} color="#0284c7" />
        <Text style={styles.title}>AI PATIENT INSIGHTS</Text>
      </View>

      <View
        style={[
          styles.card,
          insight.isBusy ? styles.busyBorder : styles.normalBorder,
        ]}
      >
        <Text style={styles.peakLabel}>
          PROSPECTIVE PEAK TIME: {insight.peakTime}
        </Text>
        <Text style={styles.suggestionText}>{insight.suggestion}</Text>

        <View style={styles.aiBadge}>
          <Ionicons name="robot-outline" size={12} color="#0284c7" />
          <Text style={styles.aiText}>Generated by UniHealth Analytics</Text>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { marginTop: 20, marginBottom: 10 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  title: { fontSize: 11, fontWeight: '800', color: '#64748b', letterSpacing: 1 },
  card: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 15,
    borderLeftWidth: 4,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  busyBorder: { borderLeftColor: '#f59e0b' },
  normalBorder: { borderLeftColor: '#10b981' },
  peakLabel: { fontSize: 12, fontWeight: '700', color: '#1e293b', marginBottom: 5 },
  suggestionText: { fontSize: 13, color: '#475569', lineHeight: 18 },
  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  aiText: { fontSize: 10, color: '#0284c7', fontWeight: '600' },
});
