import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import Ionicons from "@expo/vector-icons/Ionicons";
import { getDatabase, ref, onValue } from "firebase/database";

export default function SystemHealthMonitor({ hospitalId = "UH-HOS-00000" }) {
  const [stats, setStats] = useState({
    totalEvents: 0,
    criticalSignals: 0,
    status: "Normal",
    aiInsight: "Scanning recent activity..."
  });

  useEffect(() => {
    const db = getDatabase();
    // Listening to the Audit metadata generated by Member 2's Admin Panel
    const auditRef = ref(db, `Hospitals/${hospitalId}/auditSummary`);
    
    const unsubscribe = onValue(auditRef, (snapshot) => {
      if (snapshot.exists()) {
        setStats(snapshot.val());
      } else {
        // Fallback to static data from Member 2's HTML
        setStats({
          totalEvents: 142,
          criticalSignals: 2,
          status: "Live Tracking",
          aiInsight: "Emergency mode recently updated to 'Busy'. ICU beds are at 90% capacity."
        });
      }
    });

    return () => unsubscribe();
  }, [hospitalId]);

  return (
    <View style={styles.container}>
      {/* KPI Row - Replicated from Audit KPI Pills */}
      <View style={styles.kpiRow}>
        <View style={[styles.kpiPill, { backgroundColor: '#e0f2fe' }]}>
          <Text style={[styles.kpiLabel, { color: '#0369a1' }]}>TOTAL EVENTS</Text>
          <Text style={[styles.kpiValue, { color: '#0c4a6e' }]}>{stats.totalEvents}</Text>
        </View>
        <View style={[styles.kpiPill, { backgroundColor: '#fee2e2' }]}>
          <Text style={[styles.kpiLabel, { color: '#b91c1c' }]}>CRITICAL SIGNALS</Text>
          <Text style={[styles.kpiValue, { color: '#7f1d1d' }]}>{stats.criticalSignals}</Text>
        </View>
      </View>

      {/* AI Summary Card - Replicated from Audit AI Box */}
      <View style={styles.aiBox}>
        <View style={styles.aiHeader}>
          <View style={styles.aiAvatar}>
            <Ionicons name="analytics" size={16} color="#0891b2" />
          </View>
          <Text style={styles.aiTitle}>AI ACTIVITY INSIGHT</Text>
          <View style={styles.liveBadge}>
            <View style={styles.dot} />
            <Text style={styles.liveText}>LIVE</Text>
          </View>
        </View>
        <Text style={styles.aiText}>{stats.aiInsight}</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { padding: 15, backgroundColor: '#f8fafc' },
  kpiRow: { flexDirection: 'row', gap: 10, marginBottom: 15 },
  kpiPill: { flex: 1, padding: 12, borderRadius: 12, alignItems: 'center' },
  kpiLabel: { fontSize: 9, fontWeight: '800', marginBottom: 4 },
  kpiValue: { fontSize: 18, fontWeight: '900' },
  aiBox: { 
    backgroundColor: '#fff', 
    borderRadius: 16, 
    padding: 15, 
    borderLeftWidth: 4, 
    borderLeftColor: '#0891b2',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4
  },
  aiHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  aiAvatar: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#ecfeff', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  aiTitle: { fontSize: 11, fontWeight: '800', color: '#1e293b', flex: 1 },
  aiText: { fontSize: 13, color: '#475569', lineHeight: 18 },
  liveBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#dcfce7', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#22c55e', marginRight: 5 },
  liveText: { fontSize: 9, fontWeight: '900', color: '#166534' }
});